tunnel: njupt-aisci
credentials-file: ~/.cloudflared/credentials.json
metrics: 127.0.0.1:8080

ingress:
  - hostname: aisci.yourdomain.com
    service: http://localhost:5173
    originRequest:
      httpHostHeader: aisci.yourdomain.com
      http2Origin: true
      connectTimeout: 120s
      tcpKeepAlive: 30s
      noTLSVerify: false
      disableChunkedEncoding: false
  - service: http_status:404

warp-routing:
  enabled: false